openapi: 3.0.2
info:
  version: 0.0.2
  description: Attendance API
  title: 出退勤API
servers:
  - url: "{baseUrl}"
    description: Do not discribe actual server URL. This parameter should be given by each envioronment config of application.
    variables:
      baseUrl:
        default: 'http://localhost:10010/api/attendance'
paths:
  '/attendance':
    get:
      description: 個別ユーザの出退勤情報取得
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserAttendanceResponse'
          description: OK
        '400':
          description: |
            不正なユーザIDです
        '404':
          description: |
            ユーザが見つかりませんでした
      operationId: getUserAttendance
      summary: GetUserAttendance
      security:
        - userPool: []
      tags:
        - attendance
      parameters:
        - name: from
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: false
          schema:
            type: string
            format: date
    post:
      description: 個別ユーザの出退勤情報追加
      operationId: postUserAttendance
      summary: PostUserAttendance
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceResponse'
        '401':
          description: 認証が必要です。
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      security:
        - userPool: []
      tags:
        - attendance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttendanceRequest'
        description: '個別ユーザの出退勤情報'
components:
  schemas:
    AttendanceRequest:
      type: object
      description: 出退勤情報
      properties:
        action:
          type: string
        memo:
          type: string
      required:
        - action
      x-tags:
        - attendance
    AttendanceResponse:
      type: object
      description: 出退勤情報
      properties:
        id:
          type: string
        uid:
          type: string
        date:
          type: string
          format: date-time
        action:
          type: string
        memo:
          type: string
      x-tags:
        - attendance
    GetUserAttendanceResponse:
      title: GetUserAttendanceResponse
      type: object
      x-tags:
        - attendance
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AttendanceResponse'
      required:
        - data
    ErrorDetail:
      title: ErrorDetail
      type: object
      x-tags:
        - attendance
      properties:
        type:
          type: string
        title:
          type: string
      required:
        - type
        - title
  securitySchemes:
    userPool:
      type: apiKey
      name: Authorization
      in: header
